---
version: 0.2

phases:
  install:
    commands:
      - |
        if [ "${SPEL_CI}" = "true" ]
        then
          SPEL_VERSION=$(date +%Y.%m.dev%s)
          export SPEL_VERSION
        fi
  build:
    commands:
      - make
  post_build:
    commands:
      - make post_build

artifacts:
  files:
    - '**/*'
  base-directory: '.spel'
